# Generated by Django 4.2.2 on 2023-06-25 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pril", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagefront",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
